#######################################################################################
# A default configuration that will be loaded for all jupyter books
# Users are expected to override these values in their own `_config.yml` file.
# This is also the "master list" of all allowed keys and values.

#######################################################################################
# Book settings
title: Spatial Database Development in Practice
author: Prof. Jonathan Pando Ocón
logo: img/logo.png
copyright: "2024"

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://jpocon.github.io/
  repository_provider: github
  path_to_book: spatial-database
  branch: main

sphinx:
  recursive_update: true
  config:
    html_theme_options:
      repository_provider: custom

